### ISSUE TITLE
vmlinux is not a bootable kernel image file and therefore cannot be used directly as a WSL2 kernel

### ISSUE THREAD

**Issue by cookieiz** [Nevuly/WSL2-Linux-Kernel-Rolling#1]
You should not build and publish the release vmlinux file in the CI workflow set up by GitHub Action, which is ${{ matrix.image-name }}, vmlinux is not a bootable kernel image file and therefore cannot be used directly as a WSL2 kernel.

vmlinux is a statically linked executable format for the Linux kernel. It is uncompressed kernel code that is typically used to develop, debug, and analyze the kernel. Of course, you can also boot a system with the VMlinux kernel by adding further boot and decompression capabilities.

For WSL2, you should use the bzImage file as the kernel (Image for arm64 architecture). bzImage(Image) is a compressed bootable Linux kernel image file that boots the Linux operating system. It is compressed from the vmlinux file. , your CI workflow file build.yml should be modified as follows:

```yaml
name: Build Kernel CI

on:
  push:
    tags:
      - 'linux-wsl-stable-6.3.[0-9]+'
  workflow_dispatch:
run-name: Stable Release Build ${{ github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: nevuly/nevuly-dev-base:arch
    strategy:
      matrix:
        include:
          - arch: x86
            image-name: wsl-stable-kernel-x86_64
          - arch: arm64
            image-name: wsl-stable-kernel-arm64
    env:
      TAG_VERSION: '${{ github.ref_name }}'

    steps:
      - name: Trust this directory
        run: git config --global --add safe.directory /__w/WSL2-Linux-Kernel-Rolling/WSL2-Linux-Kernel-Rolling

      - uses: actions/checkout@main

      - name: Download Kernel
        shell: bash
        run: |
          git clone https://github.com/Nevuly/WSL2-Linux-Kernel-Rolling.git --depth 1 -b $TAG_VERSION linux

      - name: Build Kernel
        run: |
          cd linux
          if [ ${{ matrix.arch }} == "x86" ]
          then
          echo "Build X86 Kernel"
          make KCONFIG_CONFIG=arch/x86/configs/config-wsl-x86 -j$(echo `nproc` + 1 | bc)
          cp arch/x86/boot/bzImage ../${{ matrix.image-name }}
          mkdir -p ${{ matrix.image-name }}-modules_install && make modules_install INSTALL_MOD_PATH=${{ matrix.image-name }}-modules_install
          tar -czf ${{ matrix.image-name }}-modules_install.tar.gz ${{ matrix.image-name }}-modules_install && mv ${{ matrix.image-name }}-modules_install.tar.gz ../
          else
          echo "Build ARM64 Kernel"
          export ARCH=arm64 && export CROSS_COMPILE=aarch64-linux-gnu-
          make KCONFIG_CONFIG=arch/arm64/configs/config-wsl-arm64 -j$(echo `nproc` + 1 | bc)
          cp arch/arm64/boot/Image ../${{ matrix.image-name }}
          mkdir -p ${{ matrix.image-name }}-modules_install && make modules_install INSTALL_MOD_PATH=${{ matrix.image-name }}-modules_install
          tar -czf ${{ matrix.image-name }}-modules_install.tar.gz ${{ matrix.image-name }}-modules_install && mv ${{ matrix.image-name }}-modules_install.tar.gz ../
          fi
          cd .. && sha256sum ${{ matrix.image-name }} > ${{ matrix.image-name }}.sha256
          sha256sum ${{ matrix.image-name }}-modules_install.tar.gz > ${{ matrix.image-name }}-modules_install.sha256

      - name: Upload bzImage
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.image-name }}
          path: |
            ${{ matrix.image-name }}
            ${{ matrix.image-name }}.sha256
            ${{ matrix.image-name }}-modules_install.tar.gz
            ${{ matrix.image-name }}-modules_install.sha256
  
```
